#
# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: v1
kind: Secret
metadata:
  name: cdb1-secret
  namespace: oracle-database-operator-system
type: Opaque 
data: 
  ords_pwd: "d2VsY29tZTE=" 
  sysadmin_pwd: "V0VsY29tZV8xMiMj"
  cdbadmin_user: "QyMjREJBUElfQ0RCX0FETUlO"
  cdbadmin_pwd: "V0VsY29tZV8xMiMj"
  webserver_user: "c3FsX2FkbWlu"
  webserver_pwd: "d2VsY29tZTE="