# example
apiVersion: observability.oracle.com/v4
kind: DatabaseObserver
metadata:
  name: obs-sample
  labels:
    app.kubernetes.io/name: observability-exporter
    app.kubernetes.io/instance: obs-sample
    app.kubernetes.io/version: latest
spec:
  database:
    dbUser:
      key: "username"
      secret: db-secret

    dbPassword:
      vaultSecretName: sample_secret
      vaultOCID: ocid1.vault.oc1.<region>.<vault-ocid>

    dbConnectionString:
      key: "connection"
      secret: db-secret

    dbWallet:
      secret: instance-wallet

  inherit_labels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - app.kubernetes.io/version

  prometheus:
    serviceMonitor:
      labels:
        release: prometheus

  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey