#
# Copyright (c) 2022, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
---
apiVersion: database.oracle.com/v4
kind: ShardingDatabase
metadata:
  name: shardingdatabase-sample
  namespace: shns
spec:
 shard:
    - name: shard1
      storageSizeInGb: 50
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvMatchLabels:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvAnnotations:
        volume.beta.kubernetes.io/oci-volume-source: ocid1.volume.oc1.phx.abyhqljr3z3w72t6ay5eud7d5w3kdfhktfp6gwb6euy5tzwfaxgmbvwqlvsq
      imagePullPolicy: "Always"
      shardGroup: shardgroup1
      shardRegion: primary
    - name: shard2
      storageSizeInGb: 50
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvMatchLabels:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvAnnotations:
        volume.beta.kubernetes.io/oci-volume-source: ocid1.volume.oc1.phx.abyhqljr3z3w72t6ay5eud7d5w3kdfhktfp6gwb6euy5tzwfaxgmbvwqlvsq
      imagePullPolicy: "Always"
      shardGroup: shardgroup1
      shardRegion: primary
    - name: shard3
      storageSizeInGb: 50
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvMatchLabels:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvAnnotations:
        volume.beta.kubernetes.io/oci-volume-source: ocid1.volume.oc1.phx.abyhqljr3z3w72t6ay5eud7d5w3kdfhktfp6gwb6euy5tzwfaxgmbvwqlvsq
      imagePullPolicy: "Always"
      shardGroup: shardgroup1
      shardRegion: primary
 catalog:
    - name: catalog
      storageSizeInGb: 50
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvMatchLabels:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvAnnotations:
        volume.beta.kubernetes.io/oci-volume-source: ocid1.volume.oc1.phx.abyhqljr3z3w72t6ay5eud7d5w3kdfhktfp6gwb6euy5tzwfaxgmbvwqlvsq
      imagePullPolicy: "Always"
 gsm:
    - name: gsm1
      imagePullPolicy: "Always"
      storageSizeInGb: 50
      region: primary
    - name: gsm2
      imagePullPolicy: "Always"
      storageSizeInGb: 50
      region: standby
 storageClass: oci
 dbImage: container-registry.oracle.com/database/enterprise:latest
 dbImagePullSecret: ocr-reg-cred
 gsmImage: container-registry.oracle.com/database/gsm:latest
 gsmImagePullSecret: ocr-reg-cred
 replicationType: "native"
 isExternalSvc: False
 isDeleteOraPvc: True
 isClone: True
 dbSecret:
   name: db-user-pass-rsa
   pwdFileName: pwdfile.enc
   keyFileName: key.pem
 gsmService:
   - name: oltp_rw_svc
     role: primary
   - name: oltp_ro_svc
     role: primary
