//go:build !ignore_autogenerated

/*
** Copyright (c) 2022 Oracle and/or its affiliates.
**
** The Universal Permissive License (UPL), Version 1.0
**
** Subject to the condition set forth below, permission is hereby granted to any
** person obtaining a copy of this software, associated documentation and/or data
** (collectively the "Software"), free of charge and under any and all copyright
** rights in the Software, and any and all patent rights owned or freely
** licensable by each licensor hereunder covering either (i) the unmodified
** Software as contributed to or provided by such licensor, or (ii) the Larger
** Works (as defined below), to deal in both
**
** (a) the Software, and
** (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
** one is included with the Software (each a "Larger Work" to which the Software
** is contributed by such licensors),
**
** without restriction, including without limitation the rights to copy, create
** derivative works of, display, perform, and distribute the Software and make,
** use, sell, offer for sale, import, export, have made, and have sold the
** Software and the Larger Work(s), and to sublicense the foregoing rights on
** either these or other terms.
**
** This license is subject to the following condition:
** The above copyright notice and either this complete permission notice or at
** a minimum a reference to the UPL must be included in all copies or
** substantial portions of the Software.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
** AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
** LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
** OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
** SOFTWARE.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v4

import ()

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NginxTrafficManagerSpec.
func (in *NginxTrafficManagerSpec) DeepCopy() *NginxTrafficManagerSpec {
	if in == nil {
		return nil
	}
	out := new(NginxTrafficManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NginxTrafficManagerStatus.
func (in *NginxTrafficManagerStatus) DeepCopy() *NginxTrafficManagerStatus {
	if in == nil {
		return nil
	}
	out := new(NginxTrafficManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficManagerConfigSpec) DeepCopyInto(out *TrafficManagerConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficManagerConfigSpec.
func (in *TrafficManagerConfigSpec) DeepCopy() *TrafficManagerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficManagerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficManagerEnvVar) DeepCopyInto(out *TrafficManagerEnvVar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficManagerEnvVar.
func (in *TrafficManagerEnvVar) DeepCopy() *TrafficManagerEnvVar {
	if in == nil {
		return nil
	}
	out := new(TrafficManagerEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficManagerRuntimeSpec.
func (in *TrafficManagerRuntimeSpec) DeepCopy() *TrafficManagerRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficManagerRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficManagerSecuritySpec) DeepCopyInto(out *TrafficManagerSecuritySpec) {
	*out = *in
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficManagerSecuritySpec.
func (in *TrafficManagerSecuritySpec) DeepCopy() *TrafficManagerSecuritySpec {
	if in == nil {
		return nil
	}
	out := new(TrafficManagerSecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficManagerServiceEndpointSpec.
func (in *TrafficManagerServiceEndpointSpec) DeepCopy() *TrafficManagerServiceEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficManagerServiceEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficManagerServiceSpec.
func (in *TrafficManagerServiceSpec) DeepCopy() *TrafficManagerServiceSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficManagerServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficManagerSpec.
func (in *TrafficManagerSpec) DeepCopy() *TrafficManagerSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficManagerStatus.
func (in *TrafficManagerStatus) DeepCopy() *TrafficManagerStatus {
	if in == nil {
		return nil
	}
	out := new(TrafficManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficManagerTLSSpec) DeepCopyInto(out *TrafficManagerTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficManagerTLSSpec.
func (in *TrafficManagerTLSSpec) DeepCopy() *TrafficManagerTLSSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficManagerTLSSpec)
	in.DeepCopyInto(out)
	return out
}
