#
# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: database.oracle.com/v4
kind: PDB
metadata:
  name: pdb1
  namespace: oracle-database-operator-system
  labels:
    cdb: cdb-dev
spec:
  cdbResName: "cdb-dev"
  cdbName: "DB12"
  pdbName: "pdbdev"
  adminName:
    secret:
      secretName: pdb1-secret
      key: "sysadmin_user"
  adminPwd:
    secret:
      secretName: pdb1-secret
      key: "sysadmin_pwd"
  pdbTlsKey:
    secret:
      secretName: "db-tls"
      key: "tls.key"
  pdbTlsCrt:
    secret:
      secretName: "db-tls"
      key: "tls.crt"
  pdbTlsCat:
    secret:
      secretName: "db-ca"
      key: "ca.crt"
  tdePassword:
    secret:
      secretName: "tde1-secret"
      key: "tdepassword"
  tdeSecret:
    secret:
      secretName: "tde1-secret"
      key: "tdesecret"
  totalSize: 1G
  tempSize: "100M"
  unlimitedStorage: true
  reuseTempFile: true
  fileNameConversions: NONE
  sourceFileNameConversions: "NONE"
  copyAction: "MOVE"
  action: "Plug"
  xmlFileName: /home/oracle/unplugpdb.xml
  tdeImport: true
  tdeKeystorePath: /home/oracle/keystore

