#
# Copyright (c) 2022, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml
