
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v1alpha1-cdb
  failurePolicy: Fail
  name: mcdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v1alpha1-pdb
  failurePolicy: Fail
  name: mpdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v1alpha1-singleinstancedatabase
  failurePolicy: Fail
  name: msingleinstancedatabase.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - singleinstancedatabases
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-cdb
  failurePolicy: Fail
  name: vcdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-pdb
  failurePolicy: Fail
  name: vpdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - pdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-singleinstancedatabase
  failurePolicy: Fail
  name: vsingleinstancedatabase.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - singleinstancedatabases
  sideEffects: None
