---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v4-autonomousdatabasebackup
  failurePolicy: Fail
  name: mautonomousdatabasebackupv4.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabasebackups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v4-cdb
  failurePolicy: Fail
  name: mcdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - cdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v4-dbcssystem
  failurePolicy: Fail
  name: mdbcssystemv4.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbcssystems
  sideEffects: None
- admissionReviewVersions:
  - v4
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v4-lrest
  failurePolicy: Fail
  name: mlrest.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - lrests
  sideEffects: None
- admissionReviewVersions:
  - v4
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v4-lrpdb
  failurePolicy: Fail
  name: mlrpdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - lrpdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v4-pdb
  failurePolicy: Fail
  name: mpdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - pdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v4-shardingdatabase
  failurePolicy: Fail
  name: mshardingdatabasev4.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - shardingdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v1alpha1-autonomousdatabasebackup
  failurePolicy: Fail
  name: mautonomousdatabasebackupv1alpha1.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabasebackups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v1alpha1-dataguardbroker
  failurePolicy: Fail
  name: mdataguardbroker.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dataguardbrokers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v4-dbcssystem
  failurePolicy: Fail
  name: mdbcssystemv1alpha1.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbcssystems
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v1alpha1-oraclerestdataservice
  failurePolicy: Fail
  name: moraclerestdataservice.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oraclerestdataservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v1alpha1-shardingdatabase
  failurePolicy: Fail
  name: mshardingdatabasev1alpha1.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shardingdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v1alpha1-shardingdatabase
  failurePolicy: Fail
  name: mshardingdatabase.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shardingdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-oracle-com-v1alpha1-singleinstancedatabase
  failurePolicy: Fail
  name: msingleinstancedatabase.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - singleinstancedatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-observability-oracle-com-v1-databaseobserver
  failurePolicy: Fail
  name: mdatabaseobserver.kb.io
  rules:
  - apiGroups:
    - observability.oracle.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databaseobservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-observability-oracle-com-v1alpha1-databaseobserver
  failurePolicy: Fail
  name: mdatabaseobserver.kb.io
  rules:
  - apiGroups:
    - observability.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databaseobservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-observability-oracle-com-v4-databaseobserver
  failurePolicy: Fail
  name: mdatabaseobserver.kb.io
  rules:
  - apiGroups:
    - observability.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - databaseobservers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v4-autonomouscontainerdatabase
  failurePolicy: Fail
  name: vautonomouscontainerdatabasev4.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomouscontainerdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v4-autonomousdatabasebackup
  failurePolicy: Fail
  name: vautonomousdatabasebackupv4.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabasebackups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v4-autonomousdatabaserestore
  failurePolicy: Fail
  name: vautonomousdatabaserestorev4.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabaserestores
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v4-cdb
  failurePolicy: Fail
  name: vcdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - cdbs
  sideEffects: None
- admissionReviewVersions:
  - v4
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v4-lrest
  failurePolicy: Fail
  name: vlrest.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - lrests
  sideEffects: None
- admissionReviewVersions:
  - v4
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v4-lrpdb
  failurePolicy: Fail
  name: vlrpdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - lrpdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v4-pdb
  failurePolicy: Fail
  name: vpdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - pdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v4-shardingdatabase
  failurePolicy: Fail
  name: vshardingdatabasev4.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - shardingdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-autonomouscontainerdatabase
  failurePolicy: Fail
  name: vautonomouscontainerdatabasev1alpha1.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomouscontainerdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-autonomousdatabasebackup
  failurePolicy: Fail
  name: vautonomousdatabasebackupv1alpha1.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabasebackups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-autonomousdatabaserestore
  failurePolicy: Fail
  name: vautonomousdatabaserestorev1alpha1.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabaserestores
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-autonomousdatabase
  failurePolicy: Fail
  name: vautonomousdatabasev1alpha1.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-dataguardbroker
  failurePolicy: Fail
  name: vdataguardbroker.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dataguardbrokers
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-oraclerestdataservice
  failurePolicy: Fail
  name: voraclerestdataservice.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oraclerestdataservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-shardingdatabase
  failurePolicy: Fail
  name: vshardingdatabasev1alpha1.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - shardingdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-shardingdatabase
  failurePolicy: Fail
  name: vshardingdatabase.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - shardingdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-oracle-com-v1alpha1-singleinstancedatabase
  failurePolicy: Fail
  name: vsingleinstancedatabase.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - singleinstancedatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-observability-oracle-com-v1-databaseobserver
  failurePolicy: Fail
  name: vdatabaseobserver.kb.io
  rules:
  - apiGroups:
    - observability.oracle.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databaseobservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-observability-oracle-com-v1alpha1-databaseobserver
  failurePolicy: Fail
  name: vdatabaseobserver.kb.io
  rules:
  - apiGroups:
    - observability.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databaseobservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-observability-oracle-com-v4-databaseobserver
  failurePolicy: Fail
  name: vdatabaseobserver.kb.io
  rules:
  - apiGroups:
    - observability.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - databaseobservers
  sideEffects: None
