apiVersion: database.oracle.com/v4
kind: PDB
metadata:
  name: pdb4
  namespace: pdbnamespace
  labels:
    cdb: cdb-dev
spec:
  cdbResName: "cdb-dev"
  cdbNamespace: "cdbnamespace"
  cdbName: "DB12"
  pdbName: "new_clone2"
  srcPdbName: "pdbprd"
  fileNameConversions: "NONE"
  totalSize: "UNLIMITED"
  tempSize: "UNLIMITED"
  assertivePdbDeletion: true
  action: "Clone"
  adminName:
    secret:
      secretName: "pdb-secret"
      key: "sysadmin_user"
  adminPwd:
    secret:
      secretName: "pdb-secret"
      key: "sysadmin_pwd"
  pdbTlsKey:
    secret:
      secretName: "db-tls"
      key: "tls.key"
  pdbTlsCrt:
    secret:
      secretName: "db-tls"
      key: "tls.crt"
  pdbTlsCat:
    secret:
      secretName: "db-ca"
      key: "ca.crt"
  webServerUser:
    secret:
      secretName: "pdb-secret"
      key: "webserver_user"
  webServerPwd:
    secret:
      secretName: "pdb-secret"
      key: "webserver_pwd"
