apiVersion: database.oracle.com/v4
kind: PDB
metadata:
  name: pdb2
  namespace: pdbnamespace
  labels:
    cdb: cdb-dev
spec:
  cdbResName: "cdb-dev"
  cdbNamespace: "cdbnamespace"
  cdbName: "DB12"
  pdbName: "pdbprd"
  assertivePdbDeletion: true
  fileNameConversions: "NONE"
  totalSize: "1G"
  tempSize: "100M"
  action: "Map"
  adminName:
    secret:
      secretName: "pdbusr"
      key: "e_pdbusr.txt"
  adminPwd:
    secret:
      secretName: "pdbpwd"
      key: "e_pdbpwd.txt"
  pdbTlsKey:
    secret:
      secretName: "db-tls"
      key: "tls.key"
  pdbTlsCrt:
    secret:
      secretName: "db-tls"
      key: "tls.crt"
  pdbTlsCat:
    secret:
      secretName: "db-ca"
      key: "ca.crt"
  webServerUser:
    secret:
      secretName: "wbuser"
      key: "e_wbuser.txt"
  webServerPwd:
    secret:
      secretName: "wbpass"
      key: "e_wbpass.txt"
  pdbOrdsPrvKey:
    secret:
      secretName: "prvkey"
      key: "privateKey"
