apiVersion: database.oracle.com/v4
kind: PDB
metadata:
  name: pdb1
  namespace: pdbnamespace
  labels:
    cdb: cdb-dev
spec:
  cdbResName: "cdb-dev"
  cdbNamespace: "cdbnamespace"
  cdbName: "DB12"
  pdbName: "pdbdev"
  xmlFileName: "/tmp/pdb.xml"
  action: "plug"
  fileNameConversions: "NONE"
  sourceFileNameConversions: "NONE"
  copyAction: "MOVE"
  totalSize: "1G"
  tempSize: "100M"
  assertivePdbDeletion: true
  action: "Plug"
  adminName:
    secret:
      secretName: "pdb-secret"
      key: "sysadmin_user"
  adminPwd:
    secret:
      secretName: "pdb-secret"
      key: "sysadmin_pwd"
  pdbTlsKey:
    secret:
      secretName: "db-tls"
      key: "tls.key"
  pdbTlsCrt:
    secret:
      secretName: "db-tls"
      key: "tls.crt"
  pdbTlsCat:
    secret:
      secretName: "db-ca"
      key: "ca.crt"
  webServerUser:
    secret:
      secretName: "pdb-secret"
      key: "webserver_user"
  webServerPwd:
    secret:
      secretName: "pdb-secret"
      key: "webserver_pwd"
