apiVersion: database.oracle.com/v1alpha1
kind: OrdsSrvs
metadata:
  name: ords-multi-pool
  namespace: ordsnamespace
spec:
  image: container-registry.oracle.com/database/ords:24.1.1
  forceRestart: true
  globalSettings:
    database.api.enabled: true
  poolSettings:
    - poolName: pdb1
      autoUpgradeORDS: true
      db.connectionType: tns
      db.tnsAliasName: pdb1
      tnsAdminSecret:
        secretName: multi-tns-admin
      restEnabledSql.active: true
      feature.sdw: true
      plsql.gateway.mode: proxied
      db.username: ORDS_PUBLIC_USER
      db.secret:
        secretName: multi-ords-auth
      db.adminUser: SYS
      db.adminUser.secret:
        secretName: pdb1-priv-auth
    - poolName: pdb2
      db.connectionType: tns
      db.tnsAliasName: PDB2
      tnsAdminSecret:
        secretName:  multi-tns-admin
      restEnabledSql.active: true
      feature.sdw: true
      plsql.gateway.mode: proxied
      db.username: ORDS_PUBLIC_USER
      db.secret:
        secretName: multi-ords-auth
      db.adminUser: SYS
      db.adminUser.secret:
        secretName: pdb2-priv-auth


