#
# Copyright (c) 2021, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: database.oracle.com/v1alpha1
kind: ShardingDatabase
metadata:
  name: shardingdatabase-sample
  namespace: shns
spec:
 shard:
    - name: shard1
      storageSizeInGb: 50
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "EU-FRANKFURT-1-AD-1"
      pvMatchLabels:
        "failure-domain.beta.kubernetes.io/zone": "EU-FRANKFURT-1-AD-1"
      pvAnnotations:
        volume.beta.kubernetes.io/oci-volume-source: ocid1.volume.oc1.eu-frankfurt-1.abtheljtmwcwf7liuhaibzgdcoxqcwwfpsqiqlsumrjlzkin7y4zx3x2idua
    - name: shard2
      storageSizeInGb: 50
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "EU-FRANKFURT-1-AD-1"
      pvMatchLabels:
        "failure-domain.beta.kubernetes.io/zone": "EU-FRANKFURT-1-AD-1"
      pvAnnotations:
        volume.beta.kubernetes.io/oci-volume-source: ocid1.volume.oc1.eu-frankfurt-1.abtheljtmwcwf7liuhaibzgdcoxqcwwfpsqiqlsumrjlzkin7y4zx3x2idua
 catalog:
    - name: catalog
      storageSizeInGb: 50
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "EU-FRANKFURT-1-AD-1"
      pvMatchLabels:
        "failure-domain.beta.kubernetes.io/zone": "EU-FRANKFURT-1-AD-1"
      pvAnnotations:
        volume.beta.kubernetes.io/oci-volume-source: ocid1.volume.oc1.eu-frankfurt-1.abtheljtmwcwf7liuhaibzgdcoxqcwwfpsqiqlsumrjlzkin7y4zx3x2idua
 gsm:
    - name: gsm1
      storageSizeInGb: 50
      replicas: 1
      envVars:
        - name:  "SERVICE1_PARAMS"
          value: "service_name=oltp_rw_svc;service_role=primary"
        - name:  "SERVICE2_PARAMS"
          value: "service_name=oltp_ro_svc;service_role=primary"
    - name: gsm2
      storageSizeInGb: 50
      replicas: 1
      envVars:
        - name:  "SERVICE1_PARAMS"
          value: "service_name=oltp_rw_svc;service_role=primary"
        - name:  "SERVICE2_PARAMS"
          value: "service_name=oltp_ro_svc;service_role=primary"
 storageClass: oci
 dbImage: container-registry.oracle.com/database/enterprise:latest
 dbImagePullSecret: ocr-reg-cred
 gsmImage: container-registry.oracle.com/database/gsm:latest
 gsmImagePullSecret: ocr-reg-cred
 scriptsLocation: "set -ex;curl https://codeload.github.com/oracle/db-sharding/tar.gz/master |   tar -xz --strip=4 db-sharding-master/docker-based-sharding-deployment/dockerfiles/21.3.0/scripts; cp -i -r scripts/* /opt/oracle/scripts/sharding/scripts/;cp -i -r scripts/*py /opt/oracle/scripts/sharding"
 secret: db-user-pass
 isExternalSvc: false
 isClone: True
 isDeleteOraPvc: True
 namespace: shns
