#
# Copyright (c) 2022, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

---
# Create a Security Context Contraint

 kind: SecurityContextConstraints
 apiVersion: v1
 metadata:
   name: sidb-scc
   namespace: default
 allowPrivilegedContainer: false
 runAsUser:
   type: MustRunAsRange
   uidRangeMin: 0
   uidRangeMax: 60000
 seLinuxContext:
   type: RunAsAny
 fsGroup:
   type: MustRunAs
   ranges:
   - min: 0
     max: 60000
 supplementalGroups:
   type: MustRunAs
   ranges:
   - min: 0
     max: 60000

---
# Create Service Account

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidb-sa
  namespace: default

---
# Create a rbac role

 kind: Role
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: use-sidb-scc
   namespace: default
 rules:
   - apiGroups: ["security.openshift.io"]
     resources: ["securitycontextconstraints"]
     resourceNames: ["sidb-scc"]
     verbs: ["use"]

---
# Create a rbac role binding

 kind: RoleBinding
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: use-sidb-scc
   namespace: default
 subjects:
   - kind: ServiceAccount
     name: sidb-sa
 roleRef:
   kind: Role
   name: use-sidb-scc
   apiGroup: rbac.authorization.k8s.io
  