#
# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

## ORDS password secret
apiVersion: v1
kind: Secret
metadata:
  name: ords-secret
  namespace: default
type: Opaque
stringData:
  ## Specify your ORDS password here
  oracle_pwd: 

---

## APEX password secret
apiVersion: v1
kind: Secret
metadata:
  name: apex-secret
  namespace: default
type: Opaque
stringData:
  ## Specify your APEX password here
  ## This password should complete the following requirements:
  ## 1. Contain at least 6 characters.
  ## 2. Contain at least one numeric character (0123456789).
  ## 3. Contain at least one punctuation character (!"#$%&()``*+,-/:;?_).
  ## 4. Contain at least one uppercase alphabetic character.
  oracle_pwd: