#
# Copyright (c) 2023, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: database.oracle.com/v4
kind: OracleRestDataService
metadata:
  name: ords-sample
  namespace: default
spec:
  
  ## Database ref. This can be of kind SingleInstanceDatabase.
  ## Make sure the source database has been created.
  databaseRef: "sidb-sample"
  
  security:
    secrets:
      ## Secret containing databaseRef admin password mapped to secretKey.
      databaseAdmin:
        secretName: db-admin-secret
        secretKey: oracle_pwd
        keepSecret: true
      
      ## Secret containing ORDS_PUBLIC_USER password mapped to secretKey.
      ordsPublicUser:
        secretName: ords-secret
        secretKey: oracle_pwd
        keepSecret: true

  ## ORDS image details
  image:
    pullFrom: container-registry.oracle.com/database/ords-developer:latest

  ## Set this to true to enable MongoDB API
  mongoDbApi: true

  replicas: 1

  ## PDB Schemas to be ORDS Enabled.
  ## Schema will be created (if not exists) with password from .spec.ordsPassword.
  restEnableSchemas:
  - schemaName: schema1
    enable: true
    urlMapping: 
  - schemaName: schema2
    enable: true
    urlMapping: myschema
