#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: database.oracle.com/v1alpha1
kind: OracleRestDataService
metadata:
  name: ords-sample
  namespace: default
spec:
  
  ## Database ref. This can be of kind SingleInstanceDatabase.
  databaseRef: "singleinstancedatabase-sample"
  
  ## Secret containing databaseRef password mapped to secretKey. 
  ## This secret will be deleted after ORDS Installation unless keepSecret set to true.
  adminPassword:
    secretName: 
    secretKey:
    keepSecret: true

  ## Secret containing ORDS_PUBLIC_USER password mapped to secretKey. secretKey defaults to oracle_pwd
  ## This secret will be deleted after ORDS Installation unless keepSecret set to true.
  ordsPassword:
    secretName: 
    secretKey:
    keepSecret: true

  ## To configure APEX with ORDS, specfiy the apexPassword secret details. Leave empty if Apex is not needed.
  ## This is a secret containing a common password for APEX_PUBLIC_USER, APEX_REST_PUBLIC_USER, APEX_LISTENER and Apex administrator (username: ADMIN) mapped to secretKey
  ## This secret will be deleted after ORDS Installation unless keepSecret set to true.
  apexPassword:
    secretName: 
    secretKey:
    keepSecret: true

  ## ORDS image details
  ## Build the ORDS image following instructions at
  ## https://github.com/oracle/docker-images/tree/main/OracleRestDataServices
  image:
    pullFrom:
    pullSecrets:

  ## size : Minimum size of pvc | class : PVC storage Class
  ## AccessMode can only accept one of ReadWriteOnce, ReadWriteMany
  ## Below mentioned storageClass/accessMode applies to OCI block volumes. Update appropriately for other types of persistent volumes.
  persistence:
    size: 50Gi
    storageClass: "oci-bv"
    accessMode: "ReadWriteOnce"

  ## Type of service  Applicable on cloud enviroments only.
  ## if loadBalService: false, service type = "NodePort". else "LoadBalancer"
  loadBalancer: false

  ## Deploy only on nodes having required labels. Format label_name : label_value
  ## The same lables are applied to the created PVC
  ## For instance if the Pods and storage need to be restricted to a particular AD
  ## Leave commented if there is no such requirement.
  # nodeSelector:
  #   failure-domain.beta.kubernetes.io/zone: PHX-AD-1

  ## PDB Schemas to be ORDS Enabled.
  ## Schema will be created (if not exists) with username as schema and password as .spec.ordsPassword.
  restEnableSchemas:
  - schema:
    enable: true
    urlMapping:
    pdb:

  ## If deploying on OpenShift, change service account name to 'sidb-sa' after you run `$ oc apply -f openshift_rbac.yaml`
  serviceAccountName: default