#
# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: database.oracle.com/v1alpha1
kind: OracleRestDataService
metadata:
  name: ords-sample
  namespace: default
spec:
  
  ## Database ref. This can be of kind SingleInstanceDatabase.
  ## Make sure the source database has been created by applying singeinstancedatabase_express.yaml
  databaseRef: "xedb-sample"
  
  ## Secret containing databaseRef password
  adminPassword:
    secretName: xedb-admin-secret

  ## Secret containing ORDS_PUBLIC_USER password
  ordsPassword:
    secretName: ords-secret

  ## To configure APEX with ORDS, specfiy the apexPassword secret details. Leave empty if Apex is not needed.
  ## This is a secret containing a common password for APEX_PUBLIC_USER, APEX_REST_PUBLIC_USER, APEX_LISTENER and Apex administrator (username: ADMIN)
  apexPassword:
    secretName: apex-secret

  ## ORDS image details
  image:
    pullFrom: container-registry.oracle.com/database/ords:21.4.2-gh

  ## PDB Schemas to be ORDS Enabled.
  ## Schema will be created (if not exists) with password as .spec.ordsPassword.
  restEnableSchemas:
  - schemaName: schema1
    enable: true
    urlMapping: 
  - schemaName: schema2
    enable: true
    urlMapping: myschema
