#
# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

## Database Admin Password Secret
apiVersion: v1
kind: Secret
metadata:
  name: db-admin-secret
  namespace: default
type: Opaque
stringData:
  ## Specify your DB password here
  oracle_pwd:

---

## Prebuilt-Database Admin password secret
apiVersion: v1
kind: Secret
metadata:
  name: prebuiltdb-admin-secret
  namespace: default
type: Opaque
stringData:
  ## Specify your DB password here
  oracle_pwd:

---

## Oracle Database XE Admin password secret
apiVersion: v1
kind: Secret
metadata:
  name: xedb-admin-secret
  namespace: default
type: Opaque
stringData:
  ## Specify your DB password here
  oracle_pwd:

---

## Oracle Database Free Admin password secret
apiVersion: v1
kind: Secret
metadata:
  name: freedb-admin-secret
  namespace: default
type: Opaque
stringData:
  ## Specify your DB password here
  oracle_pwd:
