#
# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: prebuiltdb-sample
  namespace: default
spec:

  ## DB edition
  edition: free

  ## Secret containing SIDB password mapped to secretKey
  adminPassword:
    secretName: prebuiltdb-admin-secret

  ## Database Image
  image:
    pullFrom: container-registry.oracle.com/database/free:latest
    prebuiltDB: true

  ## Persistence is optional for prebuilt DB image
  ## if specified, the prebuilt DB datafiles are copied over to the persistant volume before DB startup
  #persistence:
  #  size: 50Gi
  #  storageClass: "oci-bv"
  #  accessMode: "ReadWriteOnce"

  ## Count of Database Pods.
  replicas: 1
