#
# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: database.oracle.com/v4
kind: SingleInstanceDatabase
metadata:
  name: prebuiltdb-sample
  namespace: default
spec:

  ## DB edition
  edition: free

  ## Grouped security settings.
  security:
    secrets:
      admin:
        secretName: prebuiltdb-admin-secret
        secretKey: oracle_pwd
        keepSecret: true

  ## Database Image
  image:
    pullFrom: container-registry.oracle.com/database/free:latest
    prebuiltDB: true

  ## Optional node selector to restrict the database pod to nodes having specific labels.
  ## For a single exact node, kubernetes.io/hostname can be used.
  # nodeSelector:
  #   kubernetes.io/hostname: worker-node.example

  ## Persistence is optional for prebuilt DB image
  ## if specified, the prebuilt DB datafiles are copied over to the persistant volume before DB startup
  #persistence:
  #  oradata:
  #    size: 50Gi
  #    storageClass: "oci-bv"
  #    accessMode: "ReadWriteOnce"

  ## Count of Database Pods.
  replicas: 1
