#
# Copyright (c) 2021, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: sidb-sample-patch
  namespace: default
spec:
  
  ## Use only alphanumeric characters for sid
  sid: ORCL1
  
  ## Secret containing SIDB password mapped to secretKey 
  ## This secret will be deleted after creation of the database unless keepSecret is set to true
  adminPassword:
    secretName: 
    secretKey:
    keepSecret: true

  ## Patch the database by updating the RU version/image
  ## Major version changes are not supported
  image:
    pullFrom:
    pullSecrets:

  ## size : Minimum size of pvc | class : PVC storage Class
  ## AccessMode can only accept one of ReadWriteOnce, ReadWriteMany
  ## Below mentioned storageClass/accessMode applies to OCI block volumes. Update appropriately for other types of persistent volumes.
  persistence:
    size: 100Gi
    storageClass: "oci"
    accessMode: "ReadWriteOnce"

  ## If deploying on OpenShift, change service account name to 'sidb-sa' after you run `$ oc apply -f openshift_rbac.yaml`
  serviceAccountName: default

  ## Count of Database Pods. Applicable only for "ReadWriteMany" AccessMode
  replicas: 1
