#
# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  # Creates base standbydatabase-sample. Use singleinstancedatabase_clone.yaml for cloning
  #                           and singleinstancedatabase_patch.yaml for patching
  name: standbydatabase-sample
  namespace: default
spec:
  
  ## Use only alphanumeric characters for sid
  sid: ORCLS

  ## The name of a source primary database resource from the same namespace
  primaryDatabaseRef: "sidb-sample"

  ## Intended type of database.
  createAs: standby

  ## Secret containing SIDB password mapped to secretKey 
  adminPassword:
    secretName: db-admin-secret

  ## Database image details
  image:
    pullFrom: container-registry.oracle.com/database/enterprise:latest
    pullSecrets: oracle-container-registry-secret

  ## size is the required minimum size of the persistent volume
  ## storageClass is specified for automatic volume provisioning
  ## accessMode can only accept one of ReadWriteOnce, ReadWriteMany
  persistence:
    size: 100Gi
    ## oci-bv applies to OCI block volumes. Use "standard" storageClass for dynamic provisioning in Minikube. Update as appropriate for other cloud service providers
    storageClass: "oci-bv"
    accessMode: "ReadWriteOnce"

  ## Type of service . Applicable on cloud enviroments only
  ## if loadBalService : false, service type = "NodePort" else "LoadBalancer"
  loadBalancer: false

  replicas: 1 
  