#
# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: v1
kind: Secret
metadata:
  name: xedb-admin-secret
  namespace: default
type: Opaque
stringData:
  oracle_pwd: "ChangeOnInstall_1"

---

apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: xedb-sample
  namespace: default
spec:
  
  ## Use only alphanumeric characters for sid
  sid: XE
  
  ## DB edition
  edition: express
  
  ## Secret containing SIDB password mapped to secretKey
  adminPassword:
    secretName: xedb-admin-secret
    secretKey: oracle_pwd

  ## Database image details
  image:
    pullFrom: container-registry.oracle.com/database/express:latest
    prebuiltDB: true

  ## size : Minimum size of pvc | class : PVC storage Class
  ## AccessMode can only accept one of ReadWriteOnce, ReadWriteMany
  persistence:
    size: 50Gi
    storageClass: "oci-bv"
    accessMode: "ReadWriteOnce"
