#
# Copyright (c) 2021, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: sidb-sample
  namespace: default
spec:
  
  ## Use only alphanumeric characters for sid
  sid: ORCL1
  
  ## A source database ref to clone from, leave empty to create a fresh database
  ## If cloning from on-prem source database, mention connect string `<host>:<port>/<service_name>`.
  cloneFrom: ""

  ## DB edition. N/A if cloning from a SourceDB (cloneFrom is set)
  edition: enterprise
  
  ## Should refer to SourceDB secret if cloning from a SourceDB (cloneFrom is set)
  ## Secret containing SIDB password mapped to secretKey
  ## This secret will be deleted after creation of the database unless keepSecret is set to true
  adminPassword:
    secretName: 
    secretKey:
    keepSecret: true

  ## DB character set. N/A if cloning from a SourceDB (cloneFrom is set)
  charset: AL32UTF8

  ## PDB name. N/A if cloning from a SourceDB (cloneFrom is set)
  pdbName: orclpdb1

  ## Enable/Disable Flashback
  flashBack: false

  ## Enable/Disable ArchiveLog. Should be true to allow DB cloning
  archiveLog: false

  ## Enable/Disable ForceLogging
  forceLog: false

  ## NA if cloning from a SourceDB (cloneFrom is set)
  ## Specify both sgaSize and pgaSize (in MB) or dont specify both
  ## Specify Non-Zero value to use
  initParams:
    cpuCount: 0
    processes: 0
    sgaTarget: 0
    pgaAggregateTarget: 0

  ## Database image details
  ## Base DB images are available at container-registry.oracle.com or build from https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance
  ## Build patched DB images from https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/extensions/patching
  ## If cloning from on-prem DB, build on-prem DB image following the instructions at
  ## https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance#containerizing-an-on-premise-database-supported-from-version-1930-release
  ## Prebuilt DB support (https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/extensions/prebuiltdb)
  ## Specify prebuiltDB as true if the image includes a prebuilt DB
  image:
    pullFrom:
    pullSecrets:
    prebuiltDB: false

  ## size : Minimum size of pvc | class : PVC storage Class
  ## AccessMode can only accept one of ReadWriteOnce, ReadWriteMany
  ## Below mentioned storageClass/accessMode applies to OCI block volumes. Update appropriately for other types of persistent volumes.
  persistence:
    size: 100Gi
    storageClass: "oci-bv"
    accessMode: "ReadWriteOnce"

  ## Type of service . Applicable on cloud enviroments only
  ## if loadBalService : false, service type = "NodePort". else "LoadBalancer"
  loadBalancer: false

  ## Deploy only on nodes having required labels. Format label_name : label_value
  ## The same lables are applied to the created PVC
  ## For instance if the Pods and storage need to be restricted to a particular AD
  ## Leave commented if there is no such requirement.
  # nodeSelector:
  #   failure-domain.beta.kubernetes.io/zone: PHX-AD-1

  ## If deploying on OpenShift, change service account name to 'sidb-sa' after you run `$ oc apply -f openshift_rbac.yaml`
  serviceAccountName: default

  ## Count of Database Pods. Only one pod will have the DB mounted and open.
  ## The other replica pods will have instance up and will mount and open the DB if the primary pod dies
  ## For "ReadWriteOnce" AccessMode, all the replicas will schedule on the same node that has the storage attached
  ## Express edition can only have one replica
  replicas: 1
