#
# Copyright (c) 2021, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: singleinstancedatabase-sample
  namespace: default
spec:

  ## Database Image
  image:
    pullFrom:
    pullSecrets:
