#
# Copyright (c) 2022, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
---
apiVersion: database.oracle.com/v1alpha1
kind: ShardingDatabase
metadata:
  name: shardingdatabase-sample
  namespace: shns
spec:
 shard:
    - name: shard1
      storageSizeInGb: 50
      resources:
        requests:
          memory: "1000Mi"
          cpu: "1000m"
      envVars:
        - name: "INIT_SGA_SIZE"
          value: "600"
        - name: "INIT_PGA_SIZE"
          value: "400"
      imagePullPolicy: "Always"
      shardSpace: sspace1
      shardRegion: primary
    - name: shard2
      storageSizeInGb: 50
      resources:
        requests:
          memory: "1000Mi"
          cpu: "1000m"
      envVars:
        - name: "INIT_SGA_SIZE"
          value: "600"
        - name: "INIT_PGA_SIZE"
          value: "400"
      imagePullPolicy: "Always"
      shardSpace: sspace2
      shardRegion: primary
    - name: shard3
      storageSizeInGb: 50
      resources:
        requests:
          memory: "1000Mi"
          cpu: "1000m"
      envVars:
        - name: "INIT_SGA_SIZE"
          value: "600"
        - name: "INIT_PGA_SIZE"
          value: "400"
      imagePullPolicy: "Always"
      shardSpace: sspace3
      shardRegion: primary
 catalog:
    - name: catalog
      storageSizeInGb: 50
      resources:
        requests:
          memory: "1000Mi"
          cpu: "1000m"
      imagePullPolicy: "Always"
 gsm:
    - name: gsm1
      imagePullPolicy: "Always"
      storageSizeInGb: 50
      region: primary
    - name: gsm2
      imagePullPolicy: "Always"
      storageSizeInGb: 50
      region: standby
 storageClass: oci
 dbImage: container-registry.oracle.com/database/enterprise:latest
 dbImagePullSecret: ocr-reg-cred
 gsmImage: container-registry.oracle.com/database/gsm:latest
 gsmImagePullSecret: ocr-reg-cred
 shardingType: USER
 isExternalSvc: False
 isDeleteOraPvc: True
 dbSecret:
   name: db-user-pass-rsa
   pwdFileName: pwdfile.enc
   keyFileName: key.pem
 gsmService:
   - name: oltp_rw_svc
     role: primary
   - name: oltp_ro_svc
     role: primary
 namespace: shns

