apiVersion: v1
kind: PersistentVolume
metadata:
 name: oke-fsspv
 namespace: pai
spec:
 storageClassName: oci-fss
 capacity:
  storage: 100Gi
 accessModes:
  - ReadWriteMany
 mountOptions:
  - nosuid
 nfs:
  server: XX.XX.XX.XX
  path: "/privateai_models"
  readOnly: false
