#
# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
---
# Specifies the custom resource API version
apiVersion: privateai.oracle.com/v4

# Defines the type of resource (Private AI)
kind: PrivateAi

# Provide identification and scoping metadata
metadata:
  # Name of Private AI resource
  name: pai-sample
  # Kubernetes Namespace where this resource will be deployed
  namespace: pai

# Main specification for Private AI
spec:
  security:
    authEnabled: true
    secret:
      name: paisecret
      mountLocation: /privateai/ssl
    tls:
      secretName: privateai-tls
      mountLocation: /privateai/ssl
      items:
      - key: tls.crt
        path: cert.pem
      - key: tls.key
        path: key.pem
      - key: keystore.p12
        path: keystore
  runtime:
    image:
      name: container-registry.oracle.com/database/private-ai:<new-privateai-tag>
      pullSecret: oracle-container-registry-secret
    replicas: 1
  configuration:
    configFile:
      name: privateaiconfigjson
      mountLocation: /privateai/config
  networking:
    listeners:
      https:
        enabled: true
        port: 8443
    service:
      ports:
      - port: 443
        targetPort: 8443
        protocol: TCP
      publicLoadBalancer:
        enabled: true
        ip: <<Insert Load Balancer Public IP>>
