apiVersion: database.oracle.com/v4
kind: PDB
metadata:
  name: pdb1
  namespace: pdbnamespace
  labels:
    cdb: cdb-dev
spec:
  cdbResName: "cdb-dev"
  cdbNamespace: "cdbnamespace"
  cdbName: "DB12"
  pdbName: "pdbdev"
  adminName:
    secret:
      secretName: "[...]"
      key: "[...]" 
  adminPwd:
    secret:
      secretName: "[...]"
      key: "[...]"
  pdbTlsKey:
    secret:
      secretName: "db-tls"
      key: "tls.key"
  pdbTlsCrt:
    secret:
      secretName: "db-tls"
      key: "tls.crt"
  pdbTlsCat:
    secret:
      secretName: "db-ca"
      key: "ca.crt"
  webServerUser:
    secret:
      secretName: "[...]"
      key: "[...]"
  webServerPwd:
    secret:
      secretName: "[...]"
      key: "[...]"
  pdbOrdsPrvKey:
    secret:
      secretName: "prvkey"
      key: "privateKey"
  pdbState: "CLOSE"
  modifyOption: "IMMEDIATE"
  action: "Modify"

