apiVersion: database.oracle.com/v4
kind: PDB
metadata:
  name: pdb1
  namespace: oracle-database-operator-system
  labels:
    cdb: cdb-dev
spec:
  cdbResName: "cdb-dev"
  cdbNamespace: "oracle-database-operator-system"
  pdbName: "pdbdev"
  action: "Delete"
  dropAction: "INCLUDING"
  pdbTlsKey:
    secret:
      secretName: "db-tls"
      key: "tls.key"
  pdbTlsCrt:
    secret:
      secretName: "db-tls"
      key: "tls.crt"
  pdbTlsCat:
    secret:
      secretName: "db-ca"
      key: "ca.crt"
  webServerUser:
    secret:
      secretName: "[...]"
      key: "[...]"
  webServerPwd:
    secret:
      secretName: "[...]"
      key: "[...]"
  pdbOrdsPrvKey:
    secret:
      secretName: "prvkey"
      key: "privateKey"

        
