apiVersion: v1
kind: Secret
metadata:
  name: external-dns-config
  namespace: external-dns
type: Opaque
stringData:
  oci.yaml: |
    auth:
      region: us-ashburn-1
      useWorkloadIdentity: true
    compartment: ocid1.compartment.oc1..replace-me
