#
# Copyright (c) 2022, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

# permissions for end users to edit autonomousdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autonomousdatabase-editor-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabases/status
  verbs:
  - get
