# permissions for end users to edit autonomousdatabasebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autonomousdatabasebackup-editor-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabasebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabasebackups/status
  verbs:
  - get
