# permissions for end users to view autonomousdatabasebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autonomousdatabasebackup-viewer-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabasebackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabasebackups/status
  verbs:
  - get
