# permissions for end users to view autonomouscontainerdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autonomouscontainerdatabase-viewer-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - autonomouscontainerdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - autonomouscontainerdatabases/status
  verbs:
  - get
