# permissions for end users to edit autonomouscontainerdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autonomouscontainerdatabase-editor-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - autonomouscontainerdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - autonomouscontainerdatabases/status
  verbs:
  - get
