# permissions for end users to edit autonomousdatabaserestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autonomousdatabaserestore-editor-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabaserestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabaserestores/status
  verbs:
  - get
