# permissions for end users to view cdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdb-viewer-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - cdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - cdbs/status
  verbs:
  - get
