# permissions for end users to edit cdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdb-editor-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - cdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - cdbs/status
  verbs:
  - get
