# permissions for end users to edit databaseobservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseobserver-editor-role
rules:
  - apiGroups:
      - observability.oracle.com
    resources:
      - databaseobservers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - observability.oracle.com
    resources:
      - databaseobservers/status
    verbs:
      - get