# permissions for end users to edit dataguardbrokers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataguardbroker-editor-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - dataguardbrokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - dataguardbrokers/status
  verbs:
  - get
