# permissions for end users to view dataguardbrokers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataguardbroker-viewer-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - dataguardbrokers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - dataguardbrokers/status
  verbs:
  - get
