# permissions for end users to view databaseobservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseobserver-viewer-role
rules:
  - apiGroups:
      - observability.oracle.com
    resources:
      - databaseobservers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - observability.oracle.com
    resources:
      - databaseobservers/status
    verbs:
      - get