# permissions for end users to edit dbcssystems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbcssystem-editor-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - dbcssystems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - dbcssystems/status
  verbs:
  - get
