# permissions for end users to edit lrests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lrest-editor-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - lrests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - lrests/status
  verbs:
  - get
