# permissions for end users to view lrpdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lrpdb-viewer-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - lrpdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - lrpdbs/status
  verbs:
  - get
