# permissions for end users to edit pdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pdb-editor-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - pdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - pdbs/status
  verbs:
  - get
