# permissions for end users to view pdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pdb-viewer-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - pdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - pdbs/status
  verbs:
  - get
