#
# Copyright (c) 2022, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

# permissions for end users to edit provshards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provshard-editor-role
rules:
- apiGroups:
  - sharding.oracle.com
  resources:
  - provshards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sharding.oracle.com
  resources:
  - provshards/status
  verbs:
  - get
