#
# Copyright (c) 2022, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
---
apiVersion: database.oracle.com/v1alpha1
kind: ShardingDatabase
metadata:
  name: shardingdatabase-sample
  namespace: shns
spec:
 shard:
    - name: shard1
      storageSizeInGb: 50
      imagePullPolicy: "Always"
      shardGroup: shardgroup1
      shardRegion: primary
      envVars:
        - name: "DB_EVENTS"
          value: "10798 trace name context forever, level 7:scope=spfile;immediate trace name GWM_TRACE level 263"
    - name: shard2
      storageSizeInGb: 50
      imagePullPolicy: "Always"
      shardGroup: shardgroup1
      shardRegion: primary
      envVars:
        - name: "DB_EVENTS"
          value: "10798 trace name context forever, level 7:scope=spfile;immediate trace name GWM_TRACE level 263"
    - name: shard3
      storageSizeInGb: 50
      imagePullPolicy: "Always"
      shardGroup: shardgroup1
      shardRegion: primary
      envVars:
        - name: "DB_EVENTS"
          value: "10798 trace name context forever, level 7:scope=spfile;immediate trace name GWM_TRACE level 263"
 catalog:
    - name: catalog
      storageSizeInGb: 50
      imagePullPolicy: "Always"
       envVars:
        - name: "DB_EVENTS"
          value: "10798 trace name context forever, level 7:scope=spfile;immediate trace name GWM_TRACE level 263"
 gsm:
    - name: gsm1
      imagePullPolicy: "Always"
      storageSizeInGb: 50
      region: primary
    - name: gsm2
      imagePullPolicy: "Always"
      storageSizeInGb: 50
      region: standby
 storageClass: oci
 dbImage: container-registry.oracle.com/database/enterprise:latest
 dbImagePullSecret: ocr-reg-cred
 gsmImage: container-registry.oracle.com/database/gsm:latest
 gsmImagePullSecret: ocr-reg-cred
 isExternalSvc: False
 isDeleteOraPvc: True
 dbSecret:
   name: db-user-pass-rsa
   pwdFileName: pwdfile.enc
   keyFileName: key.pem
 gsmService:
   - name: oltp_rw_svc
     role: primary
   - name: oltp_ro_svc
     role: primary
 namespace: shns
