# example
apiVersion: observability.oracle.com/v1alpha1
kind: DatabaseObserver
metadata:
  name: obs-sample
  labels:
    app.kubernetes.io/name: observability-exporter
    app.kubernetes.io/instance: obs-sample
    app.kubernetes.io/version: 1.5.1
spec:
  database:
    dbUser:
      key: "username"
      secret: db-secret

    dbPassword:
      key: "password"
      secret: db-secret

    dbConnectionString:
      key: "connection"
      secret: db-secret

    dbWallet:
      secret: instance-wallet

  inherit_labels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - app.kubernetes.io/version

  exporter:
    deployment:
      image: "container-registry.oracle.com/database/observability-exporter:1.5.1"
      args: [ "--log.level=info" ]
      commands: [ "/oracledb_exporter" ]

  prometheus:
    serviceMonitor:
      labels:
        release: prometheus

  configuration:
    configMap:
      key: "config.toml"
      name: "devcm-oradevdb-config"