apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-pdb
  namespace: pdbnamespace
data:
  rdbmsparameters.txt: |
     session_cached_cursors;100;spfile
     open_cursors;100;spfile
     db_file_multiblock_read_count;16;spfile
     test_invalid_parameter;16;spfile
