apiVersion: database.oracle.com/v4
kind: LRPDB
metadata:
  name: pdb3
  namespace: pdbnamespace
  labels:
    cdb: cdb-dev
spec:
  cdbResName: "cdb-dev"
  cdbNamespace: "cdbnamespace"
  cdbName: "DB12"
  pdbName: "new_clone"
  action: "Modify"
  pdbState: "OPEN"
  modifyOption: "READ WRITE"
  adminpdbUser:
    secret:
      secretName: "pdbusr"
      key: "e_pdbusr.txt"
  adminpdbPass:
    secret:
      secretName: "pdbpwd"
      key: "e_pdbpwd.txt"
  lrpdbTlsKey:
    secret:
      secretName: "db-tls"
      key: "tls.key"
  lrpdbTlsCrt:
    secret:
      secretName: "db-tls"
      key: "tls.crt"
  lrpdbTlsCat:
    secret:
      secretName: "db-ca"
      key: "ca.crt"
  webServerUser:
    secret:
      secretName: "wbuser"
      key: "e_wbuser.txt"
  webServerPwd:
    secret:
      secretName: "wbpass"
      key: "e_wbpass.txt"
  cdbPrvKey:
    secret:
      secretName: "prvkey"
      key: "privateKey"
