# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: autonomouscontainerdatabases.database.oracle.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: oracle-database-operator-system
          name: oracle-database-operator-webhook-service
          path: /convert
      conversionReviewVersions:
      - v1alpha1
      - v1
      - v4
