# example
apiVersion: observability.oracle.com/v4
kind: DatabaseObserver
metadata:
  name: obs-sample
spec:
  database:
    dbUser:
      key: "username"
      secret: db-secret

    dbPassword:
      key: "password"
      secret: db-secret

    dbConnectionString:
      key: "connection"
      secret: db-secret

    dbWallet:
      secret: instance-wallets

  exporter:
    deployment:
      image: "container-registry.oracle.com/database/observability-exporter:1.5.1"
      args:
        - "--log.level=info"
      commands:
        - "/oracledb_exporter"
      env:
        TNS_ADMIN: /some/custom/path
      labels:
        environment: dev
      podTemplate:
        labels:
          environment: dev
    service:
      ports:
      - name: "metrics"
        port: 9161
        targetPort: 9161
      labels:
        environment: dev

  prometheus:
    serviceMonitor:
      endpoints:
        - bearerTokenSecret:
            key: ''
          interval: 15s
          port: metrics
      labels:
        release: prometheus

