#
# Copyright (c) 2021, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: database.oracle.com/v1alpha1
kind: AutonomousContainerDatabase
metadata:
  name: autonomouscontainerdatabase-sample
spec:
  autonomousContainerDatabaseOCID: ocid1.autonomouscontainerdatabase...
  action: SYNC

  # Authorize the operator with API signing key pair. Comment out the ociConfig fields if your nodes are already authorized with instance principal.
  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey
