apiVersion: database.oracle.com/v4
kind: DbcsSystem
metadata:
  name: dbcssystem-clone
  namespace: default
spec:
  ociConfigMap: "oci-cred"
  ociSecret: "oci-privatekey"
  setupDBCloning: true
  dbBackupId: "ocid1.dbbackup.oc1.ap-mumbai-1.anrg6ljrabf7htyaae3fmnpacavkuwt2zqaj5q3gol2g6m6tirriveytoarq"
  dbClone:
    dbAdminPasswordSecret: "admin-password"
    tdeWalletPasswordSecret: "tde-password"
    dbName: "db1212"
    hostName: "host1213"
    displayName: "dbsystem01312"
    licenseModel: "BRING_YOUR_OWN_LICENSE"
    domain: "subdda0b5eaa.cluster1.oraclevcn.com"
    sshPublicKeys:
     - "oci-publickey"
    subnetId: "ocid1.subnet.oc1.ap-mumbai-1.aaaaaaaa5zpzfax66omtbmjwlv4thruyru7focnu7fjcjksujmgwmr6vpbvq"
    initialDataStorageSizeInGB: 256