apiVersion: database.oracle.com/v4
kind: DbcsSystem
metadata:
  name: dbcssystem-clone
  namespace: default
spec:
  databaseId: "ocid1.database.oc1.ap-mumbai-1.anrg6ljrabf7htyapxtsgw6hy3kyosmrawefq2csm4kjv4d5au7biuiaabsq"
  ociConfigMap: "oci-cred-mumbai"
  ociSecret: "oci-privatekey"
  setupDBCloning: true
  dbClone:
    dbAdminPaswordSecret: "admin-password"
    tdeWalletPasswordSecret: "tde-password"
    dbName: "db1212"
    hostName: "host1213"
    displayName: "dbsystem01312"
    licenseModel: "BRING_YOUR_OWN_LICENSE"
    domain: "subdda0b5eaa.cluster1.oraclevcn.com"
    sshPublicKeys:
     - "oci-publickey"
    subnetId: "ocid1.subnet.oc1.ap-mumbai-1.aaaaaaaa5zpzfax66omtbmjwlv4thruyru7focnu7fjcjksujmgwmr6vpbvq"
    initialDataStorageSizeInGB: 256