apiVersion: database.oracle.com/v4
kind: DbcsSystem
metadata:
  name: dbcssystem-create
spec:
  ociConfigMap: "oci-cred-mumbai"
  ociSecret: "oci-privatekey"
  dbSystem:
    availabilityDomain: "OLou:AP-MUMBAI-1-AD-1"
    clusterName: "maa-cluster"
    compartmentId: "ocid1.compartment.oc1..aaaaaaaa63yqilqhgxv3dszur3a2fgwc64ohpfy43vpqjm7q5zq4q4yaw72a"
    dbAdminPaswordSecret: "admin-password"
    dbBackupConfig:
      autoBackupEnabled: True
      autoBackupWindow: "SLOT_FOUR"
      recoveryWindowsInDays: 15
    dbEdition: "ENTERPRISE_EDITION_HIGH_PERFORMANCE"
    dbName: "cdb12"
    displayName: "dbsys123"
    licenseModel: "BRING_YOUR_OWN_LICENSE"
    dbVersion: "19c"
    dbWorkload: "OLTP"
    diskRedundancy: "EXTERNAL"
    hostName: "host01234"
    initialDataStorageSizeInGB: 256
    licenseModel: "BRING_YOUR_OWN_LICENSE"
    nodeCount: 2
    pdbName: "PDB0130"
    privateIp: "10.0.1.99"
    shape: "VM.Standard2.2"
    sshPublicKeys:
      - "oci-publickey"
    storageManagement: "ASM"
    subnetId: "ocid1.subnet.oc1.ap-mumbai-1.aaaaaaaa5zpzfax66omtbmjwlv4thruyru7focnu7fjcjksujmgwmr6vpbvq"
    tags:
      "TEST": "test_case_provision"
      "CreatedBy": "MAA_TEAM"
    tdeWalletPasswordSecret: "tde-password"
    timeZone: "Europe/Berlin"
