apiVersion: database.oracle.com/v1alpha1
kind: DbcsSystem
metadata:
  name: dbcssystem-create
spec:
  ociConfigMap: "oci-cred"
  ociSecret: "oci-privatekey"
  dbSystem:
    availabilityDomain: "OLou:EU-MILAN-1-AD-1" 
    compartmentId: "ocid1.compartment.oc1..aaaaaaaaks5baeqlvv4kyj2jiwnrbxgzm3gsumcfy4c6ntj2ro5i3a5gzhhq"
    dbAdminPaswordSecret: "admin-password"
    dbEdition: "ENTERPRISE_EDITION_HIGH_PERFORMANCE"
    dbName: "testdb"
    displayName: "dbsystem0130"
    licenseModel: "BRING_YOUR_OWN_LICENSE"
    dbVersion: "19c"
    dbWorkload: "OLTP"
    hostName: "host1205"
    shape: "VM.Standard2.1"
    domain: "vcndns.oraclevcn.com"
    sshPublicKeys: 
     - "oci-publickey"
    subnetId: "ocid1.subnet.oc1.eu-milan-1.aaaaaaaaeiy3tvcsnyg6upfp3ydtu7jmfnmoyifq2ax6y45b5qpdbpide5xa"

 
