apiVersion: database.oracle.com/v4
kind: DbcsSystem
metadata:
  name: dbcssystem-create
  namespace: default
spec:
  ociConfigMap: "oci-cred"
  ociSecret: "oci-privatekey"
  dbSystem:
    availabilityDomain: "OLou:US-ASHBURN-AD-1"
    compartmentId: "ocid1.compartment.oc1..aaaaaaaa63yqilqhgxv3dszur3a2fgwc64ohpfy43vpqjm7q5zq4q4yaw72a"
    dbAdminPaswordSecret: "admin-password"
    dbEdition: "ENTERPRISE_EDITION_HIGH_PERFORMANCE"
    dbName: "testdb"
    displayName: "dbsystem0130"
    licenseModel: "BRING_YOUR_OWN_LICENSE"
    dbVersion: "21c"
    dbWorkload: "OLTP"
    hostName: "host1205"
    shape: "VM.Standard2.2"
    domain: "subd215df3e6.k8stest.oraclevcn.com"
    sshPublicKeys: 
     - "oci-publickey"
    subnetId: "ocid1.subnet.oc1.iad.aaaaaaaa3lmmxwsykn2jc2vphzpq6eoyoqtte3dpwg6s5fzfkti22ibol2ua"
  kmsConfig:
    vaultName: "basdbvault"
    compartmentId: "ocid1.compartment.oc1..aaaaaaaa63yqilqhgxv3dszur3a2fgwc64ohpfy43vpqjm7q5zq4q4yaw72a"
    keyName: "dbvaultkey"