apiVersion: database.oracle.com/v4
kind: DbcsSystem
metadata:
  name: dbcssystem-create
spec:
  ociConfigMap: "oci-cred"
  ociSecret: "oci-privatekey"
  dbSystem:
    availabilityDomain: "OLou:AP-MUMBAI-1-AD-1"
    compartmentId: "ocid1.compartment.oc1..aaaaaaaa63yqilqhgxv3dszur3a2fgwc64ohpfy43vpqjm7q5zq4q4yaw72a"
    dbAdminPasswordSecret: "admin-password"
    dbEdition: "ENTERPRISE_EDITION_HIGH_PERFORMANCE"
    dbName: "kmsdb"
    displayName: "kmsdbsystem"
    licenseModel: "BRING_YOUR_OWN_LICENSE"
    dbVersion: "19c"
    dbWorkload: "OLTP"
    hostName: "kmshost"
    shape: "VM.Standard2.2"
    domain: "subdda0b5eaa.cluster1.oraclevcn.com"
    sshPublicKeys:
     - "oci-publickey"
    subnetId: "ocid1.subnet.oc1.ap-mumbai-1.aaaaaaaa5zpzfax66omtbmjwlv4thruyru7focnu7fjcjksujmgwmr6vpbvq"
  kmsConfig:
    vaultName: "dbvault"
    compartmentId: "ocid1.compartment.oc1..aaaaaaaa63yqilqhgxv3dszur3a2fgwc64ohpfy43vpqjm7q5zq4q4yaw72a"
    keyName: "dbkey"