apiVersion: database.oracle.com/v4
kind: DbcsSystem
metadata:
  name: dbcssystem-terminate
spec:
  hardLink: True
  id: "ocid1.dbsystem.oc1.phx.anyhqljrabf7htyanr3lnp6wtu5ld7qwszohiteodvwahonr2yymrftarkqa"
  ociConfigMap: "oci-cred"
  ociSecret: "oci-privatekey"
