apiVersion: database.oracle.com/v4
kind: LRPDB 
metadata:
  name: lrpdb1
  namespace: pdbnamespace
  labels:
    cdb: cdb-dev
spec:
  cdbResName: "cdb-dev"
  cdbNamespace: "cdbnamespace"
  cdbName: "DB12"
  pdbName: "pdbdev"
  lrpdbTlsKey:
    secret:
      secretName: "db-tls"
      key: "tls.key"
  lrpdbTlsCrt:
    secret:
      secretName: "db-tls"
      key: "tls.crt"
  lrpdbTlsCat:
    secret:
      secretName: "db-ca"
      key: "ca.crt"
  webServerUser:
    secret:
      secretName: "wbuser"
      key: "e_wbuser.txt"
  webServerPwd:
    secret:
      secretName: "wbpass"
      key: "e_wbpass.txt"
  cdbPrvKey:
    secret:
      secretName: "prvkey"
      key: "privateKey"
  pdbState: "CLOSE"
  modifyOption: "IMMEDIATE"
  action: "Modify"
