apiVersion: database.oracle.com/v4
kind: ShardingDatabase
metadata:
  name: shdb-inv-user-group
  namespace: shns
spec:
  storageClass: oci
  dbImage: phx.ocir.io/intsanjaysingh/db-repo/oracle/database:19.28.0.0
  gsmImage: phx.ocir.io/intsanjaysingh/db-repo/oracle/database:19.28.0.0-gsm
  shardingType: USER
  replicationType: DG
  isExternalSvc: false
  isDeleteOraPvc: true
  dbSecret:
    name: db-user-pass-rsa
    pwdFileName: pwdfile.enc
    tdePwdFileName: tdepwdfile.enc
    keyFileName: key.pem
  catalog:
    - name: catalog
      storageSizeInGb: 50
      imagePullPolicy: Always
      sharding: USER
      repl: DG
      autoVncr: OFF
      agentPort: 8080
  gsm:
    - name: gsm1
      storageSizeInGb: 50
      imagePullPolicy: Always
      region: primary
  shard:
    - name: bad1
      shardGroup: sg1
      shardSpace: ss1
