#
# Copyright (c) 2022, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: sharding.oracle.com/v1alpha1
kind: ProvShard
metadata:
  name: provshard-sample
spec:
 shard:
    - name: prod
      storageSizeInGb: 50
 catalog:
    - name: catalog
      storageSizeInGb: 50
 gsm:
    - name: gsm1
      storageSizeInGb: 50
      replicas: 1
    - name: gsm2
      storageSizeInGb: 50
      replicas: 1
 storageClass: oci
 dbImage: phx.ocir.io/intsanjaysingh/db-repo/oracle/database:21.3.0-ee
 gsmImage: phx.ocir.io/intsanjaysingh/db-repo/oracle/database-gsm:21.3.0
 secret: db-user-pass
 isExternalSvc: false
 namespace: sample-shard
