//go:build !ignore_autogenerated

/*
** Copyright (c) 2022 Oracle and/or its affiliates.
**
** The Universal Permissive License (UPL), Version 1.0
**
** Subject to the condition set forth below, permission is hereby granted to any
** person obtaining a copy of this software, associated documentation and/or data
** (collectively the "Software"), free of charge and under any and all copyright
** rights in the Software, and any and all patent rights owned or freely
** licensable by each licensor hereunder covering either (i) the unmodified
** Software as contributed to or provided by such licensor, or (ii) the Larger
** Works (as defined below), to deal in both
**
** (a) the Software, and
** (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
** one is included with the Software (each a "Larger Work" to which the Software
** is contributed by such licensors),
**
** without restriction, including without limitation the rights to copy, create
** derivative works of, display, perform, and distribute the Software and make,
** use, sell, offer for sale, import, export, have made, and have sold the
** Software and the Larger Work(s), and to sublicense the foregoing rights on
** either these or other terms.
**
** This license is subject to the following condition:
** The above copyright notice and either this complete permission notice or at
** a minimum a reference to the UPL must be included in all copies or
** substantial portions of the Software.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
** AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
** LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
** OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
** SOFTWARE.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v4

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapStatus) DeepCopyInto(out *ConfigMapStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapStatus.
func (in *ConfigMapStatus) DeepCopy() *ConfigMapStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigMapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivePrivateAiConfiguration) DeepCopyInto(out *EffectivePrivateAiConfiguration) {
	*out = *in
	if in.ConfigFile != nil {
		in, out := &in.ConfigFile, &out.ConfigFile
		*out = new(PaiConfigMap)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivePrivateAiConfiguration.
func (in *EffectivePrivateAiConfiguration) DeepCopy() *EffectivePrivateAiConfiguration {
	if in == nil {
		return nil
	}
	out := new(EffectivePrivateAiConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivePrivateAiListener) DeepCopyInto(out *EffectivePrivateAiListener) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivePrivateAiListener.
func (in *EffectivePrivateAiListener) DeepCopy() *EffectivePrivateAiListener {
	if in == nil {
		return nil
	}
	out := new(EffectivePrivateAiListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivePrivateAiListeners) DeepCopyInto(out *EffectivePrivateAiListeners) {
	*out = *in
	out.HTTP = in.HTTP
	out.HTTPS = in.HTTPS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivePrivateAiListeners.
func (in *EffectivePrivateAiListeners) DeepCopy() *EffectivePrivateAiListeners {
	if in == nil {
		return nil
	}
	out := new(EffectivePrivateAiListeners)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivePrivateAiNetworking) DeepCopyInto(out *EffectivePrivateAiNetworking) {
	*out = *in
	out.Listeners = in.Listeners
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(PaiServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodePortServices != nil {
		in, out := &in.NodePortServices, &out.NodePortServices
		*out = make([]PaiNodePortSvc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrafficManager != nil {
		in, out := &in.TrafficManager, &out.TrafficManager
		*out = new(TrafficManagerRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivePrivateAiNetworking.
func (in *EffectivePrivateAiNetworking) DeepCopy() *EffectivePrivateAiNetworking {
	if in == nil {
		return nil
	}
	out := new(EffectivePrivateAiNetworking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivePrivateAiRuntime) DeepCopyInto(out *EffectivePrivateAiRuntime) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(PrivateAiImageSpec)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvironmentVariable, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerNodes != nil {
		in, out := &in.WorkerNodes, &out.WorkerNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivePrivateAiRuntime.
func (in *EffectivePrivateAiRuntime) DeepCopy() *EffectivePrivateAiRuntime {
	if in == nil {
		return nil
	}
	out := new(EffectivePrivateAiRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivePrivateAiSecurity) DeepCopyInto(out *EffectivePrivateAiSecurity) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(PaiSecretSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(PaiTLSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivePrivateAiSecurity.
func (in *EffectivePrivateAiSecurity) DeepCopy() *EffectivePrivateAiSecurity {
	if in == nil {
		return nil
	}
	out := new(EffectivePrivateAiSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivePrivateAiSpec) DeepCopyInto(out *EffectivePrivateAiSpec) {
	*out = *in
	in.Security.DeepCopyInto(&out.Security)
	in.Runtime.DeepCopyInto(&out.Runtime)
	in.Configuration.DeepCopyInto(&out.Configuration)
	in.Storage.DeepCopyInto(&out.Storage)
	in.Networking.DeepCopyInto(&out.Networking)
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivePrivateAiSpec.
func (in *EffectivePrivateAiSpec) DeepCopy() *EffectivePrivateAiSpec {
	if in == nil {
		return nil
	}
	out := new(EffectivePrivateAiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivePrivateAiStorage) DeepCopyInto(out *EffectivePrivateAiStorage) {
	*out = *in
	if in.PvcList != nil {
		in, out := &in.PvcList, &out.PvcList
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivePrivateAiStorage.
func (in *EffectivePrivateAiStorage) DeepCopy() *EffectivePrivateAiStorage {
	if in == nil {
		return nil
	}
	out := new(EffectivePrivateAiStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariable) DeepCopyInto(out *EnvironmentVariable) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariable.
func (in *EnvironmentVariable) DeepCopy() *EnvironmentVariable {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayServiceSpec) DeepCopyInto(out *GatewayServiceSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayServiceSpec.
func (in *GatewayServiceSpec) DeepCopy() *GatewayServiceSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingSpec) DeepCopyInto(out *LoggingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingSpec.
func (in *LoggingSpec) DeepCopy() *LoggingSpec {
	if in == nil {
		return nil
	}
	out := new(LoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingStatus) DeepCopyInto(out *LoggingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingStatus.
func (in *LoggingStatus) DeepCopy() *LoggingStatus {
	if in == nil {
		return nil
	}
	out := new(LoggingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaiConfigMap) DeepCopyInto(out *PaiConfigMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaiConfigMap.
func (in *PaiConfigMap) DeepCopy() *PaiConfigMap {
	if in == nil {
		return nil
	}
	out := new(PaiConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaiExternalServiceSpec) DeepCopyInto(out *PaiExternalServiceSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaiExternalServiceSpec.
func (in *PaiExternalServiceSpec) DeepCopy() *PaiExternalServiceSpec {
	if in == nil {
		return nil
	}
	out := new(PaiExternalServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaiNodePortSvc) DeepCopyInto(out *PaiNodePortSvc) {
	*out = *in
	if in.PortMappings != nil {
		in, out := &in.PortMappings, &out.PortMappings
		*out = make([]PaiPortMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaiNodePortSvc.
func (in *PaiNodePortSvc) DeepCopy() *PaiNodePortSvc {
	if in == nil {
		return nil
	}
	out := new(PaiNodePortSvc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaiPortMapping) DeepCopyInto(out *PaiPortMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaiPortMapping.
func (in *PaiPortMapping) DeepCopy() *PaiPortMapping {
	if in == nil {
		return nil
	}
	out := new(PaiPortMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaiSecretSpec) DeepCopyInto(out *PaiSecretSpec) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretMountItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaiSecretSpec.
func (in *PaiSecretSpec) DeepCopy() *PaiSecretSpec {
	if in == nil {
		return nil
	}
	out := new(PaiSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaiServiceSpec) DeepCopyInto(out *PaiServiceSpec) {
	*out = *in
	if in.PortMappings != nil {
		in, out := &in.PortMappings, &out.PortMappings
		*out = make([]PaiPortMapping, len(*in))
		copy(*out, *in)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(PaiExternalServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaiServiceSpec.
func (in *PaiServiceSpec) DeepCopy() *PaiServiceSpec {
	if in == nil {
		return nil
	}
	out := new(PaiServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaiTLSSpec) DeepCopyInto(out *PaiTLSSpec) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretMountItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaiTLSSpec.
func (in *PaiTLSSpec) DeepCopy() *PaiTLSSpec {
	if in == nil {
		return nil
	}
	out := new(PaiTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAi) DeepCopyInto(out *PrivateAi) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAi.
func (in *PrivateAi) DeepCopy() *PrivateAi {
	if in == nil {
		return nil
	}
	out := new(PrivateAi)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateAi) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAiConfigurationSpec) DeepCopyInto(out *PrivateAiConfigurationSpec) {
	*out = *in
	if in.ConfigFile != nil {
		in, out := &in.ConfigFile, &out.ConfigFile
		*out = new(PaiConfigMap)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAiConfigurationSpec.
func (in *PrivateAiConfigurationSpec) DeepCopy() *PrivateAiConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateAiConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAiImageSpec) DeepCopyInto(out *PrivateAiImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAiImageSpec.
func (in *PrivateAiImageSpec) DeepCopy() *PrivateAiImageSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateAiImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAiList) DeepCopyInto(out *PrivateAiList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrivateAi, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAiList.
func (in *PrivateAiList) DeepCopy() *PrivateAiList {
	if in == nil {
		return nil
	}
	out := new(PrivateAiList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateAiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAiListenerSpec) DeepCopyInto(out *PrivateAiListenerSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAiListenerSpec.
func (in *PrivateAiListenerSpec) DeepCopy() *PrivateAiListenerSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateAiListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAiListenersSpec) DeepCopyInto(out *PrivateAiListenersSpec) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(PrivateAiListenerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPS != nil {
		in, out := &in.HTTPS, &out.HTTPS
		*out = new(PrivateAiListenerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAiListenersSpec.
func (in *PrivateAiListenersSpec) DeepCopy() *PrivateAiListenersSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateAiListenersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAiNetworkingSpec) DeepCopyInto(out *PrivateAiNetworkingSpec) {
	*out = *in
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = new(PrivateAiListenersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(PaiServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodePortServices != nil {
		in, out := &in.NodePortServices, &out.NodePortServices
		*out = make([]PaiNodePortSvc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrafficManager != nil {
		in, out := &in.TrafficManager, &out.TrafficManager
		*out = new(TrafficManagerRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAiNetworkingSpec.
func (in *PrivateAiNetworkingSpec) DeepCopy() *PrivateAiNetworkingSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateAiNetworkingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAiRuntimeSpec) DeepCopyInto(out *PrivateAiRuntimeSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(PrivateAiImageSpec)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvironmentVariable, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(bool)
		**out = **in
	}
	if in.ReadinessCheckPeriod != nil {
		in, out := &in.ReadinessCheckPeriod, &out.ReadinessCheckPeriod
		*out = new(int)
		**out = **in
	}
	if in.LivenessCheckPeriod != nil {
		in, out := &in.LivenessCheckPeriod, &out.LivenessCheckPeriod
		*out = new(int)
		**out = **in
	}
	if in.DownloadScripts != nil {
		in, out := &in.DownloadScripts, &out.DownloadScripts
		*out = new(bool)
		**out = **in
	}
	if in.WorkerNodes != nil {
		in, out := &in.WorkerNodes, &out.WorkerNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAiRuntimeSpec.
func (in *PrivateAiRuntimeSpec) DeepCopy() *PrivateAiRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateAiRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAiSecuritySpec) DeepCopyInto(out *PrivateAiSecuritySpec) {
	*out = *in
	if in.AuthEnabled != nil {
		in, out := &in.AuthEnabled, &out.AuthEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(PaiSecretSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(PaiTLSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAiSecuritySpec.
func (in *PrivateAiSecuritySpec) DeepCopy() *PrivateAiSecuritySpec {
	if in == nil {
		return nil
	}
	out := new(PrivateAiSecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAiSpec) DeepCopyInto(out *PrivateAiSpec) {
	*out = *in
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(PrivateAiSecuritySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(PrivateAiRuntimeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(PrivateAiConfigurationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(PrivateAiStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Networking != nil {
		in, out := &in.Networking, &out.Networking
		*out = new(PrivateAiNetworkingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingSpec)
		**out = **in
	}
	if in.PaiConfigFile != nil {
		in, out := &in.PaiConfigFile, &out.PaiConfigFile
		*out = new(PaiConfigMap)
		**out = **in
	}
	if in.PaiSecret != nil {
		in, out := &in.PaiSecret, &out.PaiSecret
		*out = new(PaiSecretSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PvcList != nil {
		in, out := &in.PvcList, &out.PvcList
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.PaiService.DeepCopyInto(&out.PaiService)
	if in.EnvVars != nil {
		in, out := &in.EnvVars, &out.EnvVars
		*out = make([]EnvironmentVariable, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodePortSvc != nil {
		in, out := &in.NodePortSvc, &out.NodePortSvc
		*out = make([]PaiNodePortSvc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PortMappings != nil {
		in, out := &in.PortMappings, &out.PortMappings
		*out = make([]PaiPortMapping, len(*in))
		copy(*out, *in)
	}
	if in.PailbAnnotation != nil {
		in, out := &in.PailbAnnotation, &out.PailbAnnotation
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.WorkerNodes != nil {
		in, out := &in.WorkerNodes, &out.WorkerNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TrafficManager != nil {
		in, out := &in.TrafficManager, &out.TrafficManager
		*out = new(TrafficManagerRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAiSpec.
func (in *PrivateAiSpec) DeepCopy() *PrivateAiSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateAiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAiStatus) DeepCopyInto(out *PrivateAiStatus) {
	*out = *in
	out.PaiSecret = in.PaiSecret
	out.TLSSecret = in.TLSSecret
	out.PaiConfigMap = in.PaiConfigMap
	out.TrafficManager = in.TrafficManager
	out.Logging = in.Logging
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAiStatus.
func (in *PrivateAiStatus) DeepCopy() *PrivateAiStatus {
	if in == nil {
		return nil
	}
	out := new(PrivateAiStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateAiStorageSpec) DeepCopyInto(out *PrivateAiStorageSpec) {
	*out = *in
	if in.PvcList != nil {
		in, out := &in.PvcList, &out.PvcList
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SizeInGb != nil {
		in, out := &in.SizeInGb, &out.SizeInGb
		*out = new(int32)
		**out = **in
	}
	if in.DeletePvcOnDelete != nil {
		in, out := &in.DeletePvcOnDelete, &out.DeletePvcOnDelete
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateAiStorageSpec.
func (in *PrivateAiStorageSpec) DeepCopy() *PrivateAiStorageSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateAiStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretMountItem) DeepCopyInto(out *SecretMountItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretMountItem.
func (in *SecretMountItem) DeepCopy() *SecretMountItem {
	if in == nil {
		return nil
	}
	out := new(SecretMountItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStatus) DeepCopyInto(out *SecretStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStatus.
func (in *SecretStatus) DeepCopy() *SecretStatus {
	if in == nil {
		return nil
	}
	out := new(SecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSecretStatus) DeepCopyInto(out *TLSSecretStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSecretStatus.
func (in *TLSSecretStatus) DeepCopy() *TLSSecretStatus {
	if in == nil {
		return nil
	}
	out := new(TLSSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficManagerRefSpec) DeepCopyInto(out *TrafficManagerRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficManagerRefSpec.
func (in *TrafficManagerRefSpec) DeepCopy() *TrafficManagerRefSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficManagerRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficManagerRefStatus) DeepCopyInto(out *TrafficManagerRefStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficManagerRefStatus.
func (in *TrafficManagerRefStatus) DeepCopy() *TrafficManagerRefStatus {
	if in == nil {
		return nil
	}
	out := new(TrafficManagerRefStatus)
	in.DeepCopyInto(out)
	return out
}
