apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabaseRestore
metadata:
  name: autonomousdatabaserestore-sample
spec:
  autonomousDatabaseOCID: ocid1.autonomousdatabase...
  destination:
    backupName: autonomousdatabasebackup-sample
    timeStamp: Oct 23, 2021 11:03:13 UTC

  # Authorize the operator with API signing key pair. Comment out the ociConfig fields if your nodes are already authorized with instance principal.
  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey

    