apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabaseRestore
metadata:
  name: autonomousdatabaserestore-sample
spec:
  # Restore the database either from a backup or using point-in-time restore
  # The name of your AutonomousDatabaseBackup resource
  backupName: autonomousdatabasebackup-sample

  # Uncomment the following block to perform point-in-time restore
  # pointInTime:
  #   autonomousDatabaseOCID: ocid1.autonomousdatabase...
  #   # The timestamp must follow this format: YYYY-MM-DD HH:MM:SS GMT
  #   timeStamp: 2021-10-23 11:03:13 UTC

  # Authorize the operator with API signing key pair. Comment out the ociConfig fields if your nodes are already authorized with instance principal.
  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey

    