apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oracle-operator-pv-role
rules:
  # PersistentVolume access (cluster-scoped)
  - apiGroups: [""]
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oracle-operator-pv-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oracle-operator-pv-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: oracle-database-operator-system
